version: '3.7'
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./src:/user/src/app/src

  postgres:
    image: postgres:10.4
    container_name: postgres
    ports:
      - '5500:5432'
    environment:
      - TZ=Asia/Dhaka
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
